config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    root 'static_pages#home'
    get  '/signup',    to: 'users#new'
    post '/signup',    to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    
    resources :users do
      member do
        get :likes
        get :followings, :followers
        get :feed
      end
    end
    resources :microposts,          only: [:new, :show, :edit, :update, :create, :destroy] do
      resources :comments,          only: [:create, :destroy]
    end
    resources :favorite_relationships, only: [:create, :destroy]
    resources :follow_relationships, only: [:create, :destroy]
    resources :notifications, only: [:index, :destroy]
    

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @microposts = if params[:tag_id].present?
                    Tag.find(params[:tag_id]).microposts
                  elsif params[:search].present?
                    Micropost.micropost_serach(params[:search]).includes(:tags, :user, :liked_by)
                  else
                    Micropost.includes(:tags, :user, :liked_by).all
                  end
    @microposts = @microposts.page(params[:page]).per(10)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_tag_search.html.erb
<%= form_with url: root_path, method: :get, class: 'tag_search' do %>
  <%= select_tag :tag_id,
    options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
    {
      prompt: 'タグ検索',
      class: 'form-control tag_select',
      onchange: 'submit(this.form);'
    }%>
<% end %>

app/views/static_pages/_title_search.html.erb
<form class="form-inline">
  <div style="display:inline-flex">
<%= form_with(url: root_path, class: 'search_searchForm', method: :get, local:true) do |f| %>
  <%= f.text_field :search,value: params[:search],class: 'form-control  title_search',\
  placeholder: "投稿を検索できます。"%><%= f.submit '検索', class: "btn badge-primary title_search_btn" %>
</div>
<% end %>
</form>

app/views/static_pages/home.html.erb
<% provide(:title,"top_page") %>

<% if !logged_in? %>
<div class="home">
  <h1>ようこそMyごはんへ。</h1>
  <h5>みんなと料理をシェアしよう。</h5>
  <P>お肉料理お魚料理なんでもOK！</P>
  <p>今日の献立に困ったら皆の投稿を参考にしよう！</p>
  <% if !logged_in? %>
  <p><%= link_to "Myごはんを始める>", "signup", class:"btn" %></p>
  <% end %>
</div>
<% end %>

<div class="microposts">
  <ol class="microposts">
    <div class="row">
      <div class="col-lg-3 offset-lg-1">
        <%= link_to "新規投稿!",new_micropost_path , class:"btn page-link text-dark d-inline-block fas fa-pen home12" %>
      </div>
    </div>



    <div class="row">

      <div class="col-lg-11 offset-lg-1">
        <div style="display:inline-flex">
        <%= render 'tag_search'%>
        <%= render 'title_search'%>
      </div>
      </div>
    </div>




    <div class="row">
      <div class="col-lg-8 offset-lg-1">
        <% if logged_in? %>
        <p><%= link_to "フォローしているユーザーの投稿のみ表示", feed_user_path(current_user), class:"btn" %></p>
        <% end %>
      </div>
    </div>

    <div class="row">
      <% if@microposts.any? %>
      <div class="col-lg-10 offset-lg-1">
        <%= render @microposts%>
        <%= paginate @microposts %>
      </div>
    </div>
  </ol>
  <% else %>
  <P>投稿がありません</P>
  <% end %>
</div>