config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    root 'static_pages#home'
    get  '/signup',    to: 'users#new'
    post '/signup',    to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    
    resources :users do
      member do
        get :likes
        get :followings, :followers
        get :feed
      end
    end
    resources :microposts,          only: [:new, :show, :edit, :update, :create, :destroy] do
      resources :comments,          only: [:create, :destroy]
    end
    resources :favorite_relationships, only: [:create, :destroy]
    resources :follow_relationships, only: [:create, :destroy]
    resources :notifications, only: [:index, :destroy]
    

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :favorite_relationships, dependent: :destroy
  has_many :likes, through: :favorite_relationships, source: :micropost

  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :active_notifications, foreign_key: 'visitor_id', class_name: 'Notification', dependent: :destroy
  has_many :passive_notifications, foreign_key: 'visited_id', class_name: 'Notification', dependent: :destroy
  # ユーザーセーブ前にemailをすべて小文字にする
  before_save { self.email = email.downcase }

  # emailフォーマット定義
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  # 名前空＋長さ50
  validates :name, presence: true, length: { maximum: 50 }

  # email空＋長さ255＋フォーマット+ユニーク（大文字）小文字区別なし

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # 空でない＋最小6文字＋ユーザー情報編集の際にパスワードがからでもOK
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/.freeze
  validates :password, presence: true,
                       allow_nil: true,
                       format: { with: VALID_PASSWORD_REGEX,
                                 message: 'は半角6~12文字英大文字・小文字・数字それぞれ１文字以上含む必要があります' }

  # authenticateメゾットが使える。パスワード一致でUserオブジェクトを返す。パスワードのバリテーションも追加
  has_secure_password

  # マイクロポストをライクする
  def like(micropost)
    likes << micropost
  end

  # マイクロポストをライク解除する
  def unlike(micropost)
    favorite_relationships.find_by(micropost_id: micropost.id).destroy
  end

  # 現在のユーザーがライクしていたらtrueを返す
  def likes?(micropost)
    likes.include?(micropost)
  end

  # すでにフォロー済みであればture返す
  def following?(other_user)
    followings.include?(other_user)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  # ユーザーのフォローを解除する
  def unfollow(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def create_notification_follow!(current_user)
    # すでに通知が作成されているか確認
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    return if temp.present?

    notification = current_user.active_notifications.new(
      visited_id: id,
      action: 'follow'
    )
    notification.save if notification.valid?
  end

  # フォローしているユーザーを取得
  def feed
    following_ids = 'SELECT following_id FROM follow_relationships WHERE follower_id =:user_id'
    Micropost.where("user_id IN (#{following_ids})
              OR user_id =:user_id", user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy likes]
  before_action :correct_user,   only: %i[edit update feed]
  before_action :correct_user_or_admin_user, only: :destroy
  def new
    # 新規ユーザ登録ページ
    @user = User.new # フォームからcreateにデーターを渡す
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'ユーザー登録完了！Myごはんへようこそ！！'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.includes(:tags, :user, :liked_by)
    @microposts = @microposts.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を編集しました‼'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to root_url
  end

  def index; end

  def likes
    @user = User.find(params[:id])
    @microposts = @user.likes.includes(:tags, :user, :liked_by).page(params[:page]).per(5)
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(5)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(5)
  end

  def feed
    @microposts = current_user.feed.page(params[:page]).per(10)
  end

  # クラス内で参照
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # 管理者確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  # ログイン中のユーザーが正しいユーザーか確認
  def correct_user?
    @user = User.find(params[:id])
    current_user?(@user)
  end

  # 管理者か正しいユーザーか確認
  def correct_user_or_admin_user
    redirect_to(root_url) unless current_user.admin? || correct_user?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.following_relationships.build) do |f| %>
  <%= f.hidden_field :following_id, value: @user.id %>
  <%= f.submit "フォロー", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with model:@user, local: true do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class = 'form-group'>
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: 'form-control' %>
</div>
<div class = 'form-group'>
      <%= f.label :email, "e-mail" %>
      <%= f.email_field :email, class: 'form-control' %>
</div>
<div class = 'form-group'>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
</div>
<div class = 'form-group'>
      <%= f.label :"password_confirmation","パスワード(確認)"  %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

      <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.following_relationships.find_by(following_id: @user.id),method: :delete) do |f| %>
  <%= f.hidden_field :following_id %>  
  <%= f.submit "フォロー中", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,"ユーザー編集") %>
<h1 class="new">ユーザー情報編集</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with model:@user, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>


     <div class = 'form-group'>
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: 'form-control' %>
     </div>
     <div class = 'form-group'>
      <%= f.label :email, "e-mail" %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

      <%= f.submit "編集", class: "btn btn-primary" %>
    <% end %>


　</div>
</div>

app/views/users/feed.html.erb
<% provide(:title,"top_page") %>

<div class="microposts">
  <ol class="microposts">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <p><%= link_to "全ての投稿を表示", root_path(current_user), class:"btn"%></p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <% if@microposts.any? %>
        <%= render @microposts%>
        <%= paginate @microposts %>
      </div>
    </div>
  </ol>
  <% else %>
  <P>投稿がありません</P>
  <% end %>
</div>
</div>
</div>

app/views/users/followers.html.erb
<% provide(:title,"フォロワー一覧") %>

<h3 class="follow_title">フォロワー</h3>
<p><%= "#{@user.followers.count}"%>人にフォローされています</p>

<div class="follo_view">
  <% if @user.followers.any? %>
    <% @users.each do |user| %>
      <p><%= link_to "#{user.name}", user_path(user)%>さんにフォローされています</p>
    <% end %>
　<% else %>
      <P>フォローされているユーザーはいません</P>
    <%=paginate @users %>
  <% end %>
</div>

app/views/users/followings.html.erb
<% provide(:title,"フォロー一覧") %>

<h3 class="follow_title">フォロー</h3>
<p><%= "#{@user.followings.count}"%>人をフォローしています</p>

<div class="follo_view">
  <% if @user.followings.any? %>
    <% @users.each do |user| %>
      <p><%= link_to "#{user.name}", user_path(user)%>さんをフォローしています。</p>
    <% end %>
　<% else %>
      <P>フォローしているユーザーはいません</P>
    <%=paginate @users %>
  <% end %>
</div>

app/views/users/likes.html.erb
<% provide(:title,"いいね一覧") %>
<div class="microposts">
    <% if @user.microposts.any? %>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
       <ol class="micro">
          <%= page_entries_info @microposts%>
          <%= render @microposts %>
          <%=paginate @microposts %>
      </ol>
    </div>
  </div>
    <% end %>
  </div>

app/views/users/new.html.erb
<% provide(:title,"新規登録") %>
<div class="container ">
<h1 class="new">新規ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
      <%= render 'form' %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title,"マイページ") %>


<div class="show">
  <div class="show_box">
    <p class="show_info text-white bg-dark">ユーザー情報</p>

    <p class="show_name">ユーザ名</p>
    <p class="show_user_name"><%= @user.name %></p>

    <% if logged_in? && @user != current_user%>
    <%= render "follow_form" %>
    <% end %>

    <div class="user_show">
      　 <p><%= link_to "いいね一覧(#{@user.likes.count})", likes_user_path(@user)%></p>
      　 <p><%= link_to "フォロー(#{@user.followings.count})", followings_user_path(@user)%>
        / <%= link_to "フォロワー(#{@user.followers.count})", followers_user_path(@user)%></p>

      <% if current_user?(@user) %>
      <p><%= link_to("編集ページへ","/users/#{@user.id}/edit") %>
      <p>
        <% end %>

        <% if admin_user? || current_user?(@user)%>
      <p><%= link_to "ユーザー削除", @user, method: :delete,
                                data: { confirm: "ユーザーを削除しますか?" } %></p>
      <% end %>
    </div>
  </div>
</div>

<div class="microposts">
  <% if @user.microposts.any? %>
  <ol class="micro">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <%= link_to "新規投稿!",new_micropost_path , class:"btn page-link text-dark d-inline-block fas fa-pen" %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <%= page_entries_info @microposts%>
        <%= render @microposts %>
        <%=paginate @microposts %>
      </div>
    </div>
  </ol>
  <% end %>
</div>

app/views/users/show_followers.html.erb
<% provide(:title,"フォロワー一覧") %>

<h3 class="follow_title">フォロワー</h3>
<p><%= "#{@user.followers.count}"%>人にフォローされています</p>

<div class="follo_view">
  <% if @user.followers.any? %>
    <% @users.each do |user| %>
      <p><%= link_to "#{user.name}", user_path(user)%>さんにフォローされています</p>
    <% end %>
　<% else %>
      <P>フォローされているユーザーはいません</P>
    <%=paginate @users %>
  <% end %>
</div>

app/views/users/show_followings.html.erb
<% provide(:title,"フォロー一覧") %>

<h3 class="follow_title">フォロワー</h3>
<p><%= "#{@user.followings.count}"%>人をフォローしています</p>

<div class="follo_view">
  <% if @user.followings.any? %>
    <% @users.each do |user| %>
      <p><%= link_to "#{user.name}", user_path(user)%>さんをフォローしています。</p>
    <% end %>
　<% else %>
      <P>フォローしているユーザーはいません</P>
    <%=paginate @users %>
  <% end %>
</div>

app/views/users/show_like.html.erb
<% content_for(:html_title) { 'Myごはん-いいね一覧' } %>
<div class="microposts">
    <% if @user.microposts.any? %>
       <ol class="micro">
         <%= link_to "新規投稿",new_micropost_path , class:"btn page-link text-dark d-inline-block" %></p>
          <%= page_entries_info @microposts%>
          <%=paginate @microposts %>
          <%= render @microposts %>
          <%=paginate @microposts %>
      </ol>
    <% end %>
  </div>