config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    root 'static_pages#home'
    get  '/signup',    to: 'users#new'
    post '/signup',    to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    
    resources :users do
      member do
        get :likes
        get :followings, :followers
        get :feed
      end
    end
    resources :microposts,          only: [:new, :show, :edit, :update, :create, :destroy] do
      resources :comments,          only: [:create, :destroy]
    end
    resources :favorite_relationships, only: [:create, :destroy]
    resources :follow_relationships, only: [:create, :destroy]
    resources :notifications, only: [:index, :destroy]
    

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_many :favorite_relationships, dependent: :destroy
  has_many :liked_by, through: :favorite_relationships, source: :user
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) } # 作成順から並ぶように
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 250 }
  validates :picture, presence: true
  validate  :picture_size

  # タグを作成・更新する
  def save_tags(savemicropost_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - savemicropost_tags
    new_tags = savemicropost_tags - current_tags

    new_tags.each do |new_name|
      micropost_tag = Tag.find_or_create_by(name: new_name)
      return false unless micropost_tag.valid?

      tags << micropost_tag
    end

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end
  end

  # タイトル・本文・コメントから検索
  def self.micropost_serach(search)
    Micropost.eager_load(:comments).where(['microposts.title LIKE ? OR microposts.content LIKE ? OR comments.content LIKE ?',
                                           "%#{search}%", "%#{search}%", "%#{search}%"])
  end

  # 通知機能
  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ',
                               current_user.id, user_id, id, 'like'])
    return if temp.present?

    notification = current_user.active_notifications.new(
      micropost_id: id,
      visited_id: user_id,
      action: 'like'
    )

    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    # 同じ投稿にコメントしているユーザーに通知を送る。（current_userと投稿ユーザーのぞく）
    temp_ids = Comment.where(micropost_id: id).where.not('user_id=? or user_id=?', current_user.id, user_id).select(:user_id).distinct
    # 取得したユーザー達へ通知を作成。（user_idのみ繰り返し取得）
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # 投稿者へ通知を作成
    save_notification_comment!(current_user, comment_id, user_id)
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      micropost_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, '5MB以上の画像はアップロードできません') if picture.size > 5.megabytes
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  include CommentActions
  before_action :logged_in_user, only: %i[new create edit update destroy]
  before_action :correct_user_micropost, only: %i[edit update destroy]

  def new
    @micropost = Micropost.new
  end

  def show
    comments_get
    @comment = Comment.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @tag_ids = params[:micropost][:tag_ids].split(',')
    if @micropost.save
      if @micropost.save_tags(@tag_ids)
        flash[:success] = '投稿しました!'
        redirect_to root_url
      else
        @tag_ids = params[:micropost][:tag_ids]
        flash.now[:danger] = '空白のタグが含まれています'
        render 'new'
      end
    else
      @tag_ids = params[:micropost][:tag_ids]
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to current_user || request.referer
  end

  def edit
    @micropost = Micropost.find(params[:id])
    @tag_ids = @micropost.tags.pluck(:name).join(',')
  end

  def update
    @micropost = Micropost.find(params[:id])
    @tag_ids = params[:micropost][:tag_ids].split(',')
    if @micropost.update(micropost_params)
      if @micropost.save_tags(@tag_ids)
        flash[:success] = '投稿を編集しました‼'
        redirect_to @micropost
      else
        @tag_ids = params[:micropost][:tag_ids]
        flash.now[:danger] = '空白のタグが含まれています'
        render 'edit'
      end
    else
      @tag_ids = params[:micropost][:tag_ids]
      render 'edit'
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture)
  end

  def correct_user_micropost
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_like.html.erb
<% if logged_in? %>
<%= form_for(current_user.favorite_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= button_tag(class: "btn page-link tex-red d-inline-block border border-0 iine" ) do %>
    <%= content_tag :span, micropost.liked_by.count, class: "far fa-heart" %>
  <% end %>
<% end %>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="card mb-3" style="max-width: 800px;">
  <div class="row no-gutters">
    <div class="col-md-4 microimage">
      <%= image_tag micropost.picture.url if micropost.picture? %>
    </div>
    <div class="col-md-8">
      
      <div class="card-body">

        <h5 class="card-title"><%= micropost.title %></h5>
        
        <p class="card-text"><%= micropost.content %></p>
        
        <span class="card-name"><%= link_to "投稿者:#{micropost.user.name}", micropost.user %></span>
        
        <p class="card-time"><small class="text-muted">
          <%= time_ago_in_words(micropost.created_at) %>前に投稿</small></p>
          
        <% micropost.tags.each do |tag| %>
            <span class="badge badge-primary micropost_tag"><%= tag.name %></span>
        <% end %>
        
        <span class="mic">
          <span class="like" id="like_form_<%= micropost.id %>">
          <% if micropost.liked_by.include?(current_user) %>
            <%= render "microposts/unlike", micropost: micropost %>
          <% else %>
            <%= render "microposts/like", micropost: micropost %>
          <% end %>
        </span>
        
        <%= link_to "コメント(#{micropost.comments.count})", micropost%>
      
        <% if current_user?(micropost.user)%>
        　 <span> <%= link_to "投稿編集", "/microposts/#{micropost.id}/edit" %></span>
        　 <span> <%= link_to "削除", micropost, method: :delete,
            data: { confirm: "投稿を削除しますか?" } %></span>
    　　<% end %>
    　　</span>
      </div>
    </div>
  </div>
</div>

app/views/microposts/_posts_form.html.erb
<%= form_with model: @micropost, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
    <div class = 'form-group'>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control',\
          placeholder: "料理名や食材名を入れてください" %>
    </div>
   
    <div class = 'form-group contentarea'>
      <%= f.label :content, "本文" %>
      <%= f.text_area :content, class: 'form-control', size: "30x10",\
         placeholder: "作った感想、味や料理のポイントなど\なんでも自由に書いて投稿しよう！" %>
    </div>
   
    <div class = 'form-group'>
      <%= f.label :picture, '料理写真' %>
      <%= f.file_field :picture,class:"form-control-file",\
          accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    
    <div class="article-tags-field">
      <%= f.text_field :tag_ids,value: @tag_ids, class: "form-control", size: "30", id:'tag_ids',\
          placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
    </div>

    <%= f.submit "投稿！", class: "btn btn-primary" %>
<% end %>
    
    
    <script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/_unlike.html.erb
<% if logged_in? %>
<%= form_for(current_user.favorite_relationships.find_by(micropost_id: micropost.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= button_tag( class: "btn page-link text-red d-inline-block border border-0 iine") do %>
    <%= content_tag :span, micropost.liked_by.count, class: "fas fa-heart" %>
  <% end %>
<% end %>
<% end %>

app/views/microposts/edit.html.erb
<% provide(:title,"投稿編集") %>

<h1 class="new">投稿編集</h1>

<%= form_with model: @micropost, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
    <div class = 'form-group'>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control',\
          placeholder: "料理名や食材名を入れてください" %>
    </div>
   
    <div class = 'form-group contentarea'>
      <%= f.label :content, "本文" %>
      <%= f.text_area :content, class: 'form-control', size: "30x10",\
         placeholder: "作った感想、味や料理のポイントなど\なんでも自由に書いて投稿しよう！" %>
    </div>
    
    <div class="article-tags-field">
      <%= f.text_field :tag_ids,value: @tag_ids, class: "form-control", size: "30", id:'tag_ids',\
          placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
    </div>

    <%= f.submit "編集", class: "btn btn-primary" %>
<% end %>
    
    
    <script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/new.html.erb
<% provide(:title,"新規投稿") %>
<div class="container ">
  <h1 class="new">新規投稿</h1>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render 'posts_form' %>
    </div>
  </div>
</div>

app/views/microposts/show.html.erb
<% provide(:title,"投稿詳細") %>
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="micropost_show">
      <%= render @micropost %>
    </div>
    <div class="mb-3" style="max-width: 800px;">
      <div class=comment_snow>
        <% @comments.each do |comment| %>
        <div class="commentbox">
          <p class="commentcontent">
            <%= comment.content %>
          </p>
          <p class="commentname">
            <%=link_to "#{comment.user.name}", comment.user %>
            <%= time_ago_in_words(comment.created_at) %>前
          </p>

          <% if current_user?(comment.user)%>
          <%= link_to '削除', micropost_comment_path(@micropost, comment), id: "commentdelete", class: 'commentdelete', method: :delete %>
          <% end %>
        </div>
        <% end %>
        <%= paginate @comments %>
      </div>

      <div class="comment_form">
        <%= form_with model: [@micropost, @comment], local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class='form-group'>
          <%= f.text_area :content, class: 'form-control',　id:'content', size: "30x5",\
         placeholder: "コメントを記入してください" %>
        </div>

        <%= f.submit "コメントする", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>