config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    root 'static_pages#home'
    get  '/signup',    to: 'users#new'
    post '/signup',    to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    
    resources :users do
      member do
        get :likes
        get :followings, :followers
        get :feed
      end
    end
    resources :microposts,          only: [:new, :show, :edit, :update, :create, :destroy] do
      resources :comments,          only: [:create, :destroy]
    end
    resources :favorite_relationships, only: [:create, :destroy]
    resources :follow_relationships, only: [:create, :destroy]
    resources :notifications, only: [:index, :destroy]
    

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
<p class="text-white bg-dark">©2020 yukihiro sato</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if logged_in? %>
  <%= link_to "ようこそ#{@current_user.name}さん‼", current_user, class: "navbar-brand far fa-laugh-beam" %>
  <% else %>
  <%= link_to "Myごはん", root_path, class: "navbar-brand fas fa-utensils" %>
   <% end %>
 
  
  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="navbar-nav">
      
      
       <% if logged_in? %>
       
      <li class="nav-item">
        <% if unchecked_notifications? %>
          <%= link_to "通知", notifications_path, class: "nav-link fas fa-flag " %>
        <% else %>
          <%= link_to "通知", notifications_path, class: "nav-link fas fa-bell " %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "投稿一覧", root_path, class: "nav-link fas fa-paste" %>
      
      <li class="nav-item">  
        <%= link_to "新規投稿", new_micropost_path, class: "nav-link fas fa-pen" %>
      </li>
      
      <li class="nav-item">
        <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link fas fa-sign-out-alt" %>
        
      </li>
      
    <% else %>
      
      
      
      
      
      <li class="nav-item">
        <%= link_to "ログイン", login_path, class: "nav-link fas fa-sign-in-alt" %>
        
      </li>
      <li class="nav-item">
        <%= link_to "新規ユーザー登録", "signup", class: "nav-link fas fa-user-plus" %>
        
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>